### PR TITLE
fix(datadog): environments variables quoted correctly

### PR DESCRIPTION
**Pull request by sebbrandt87**
fix(datadog): environments variables quoted correctly

Fix environment variables to be quoted with a loop and `quote` instead of
`toYaml`.

**Checklist**

- [x] Documentation has been updated with helm-docs (run: .github/helm-docs.sh)
- [x] Chart Version bumped
- [x] CHANGELOG.md has been updated

### CODE REVIEW

**Comment by vboulineau** [comment]
Hello @sebbrandt87,

Thanks for your contribution, however this implementation misses the handling of `valueFrom`, that's why it currently uses `toYaml`.
I think you can check for the presence of `valueFrom` and pass it through in this case.

**Comment by sebbrandt87** [comment]
Hey @vboulineau,

I added the changes, which should be now sufficient again for `valueFrom`.
Thanks for the hint! 👍

**Comment by vboulineau** [comment]
I'm thinking maybe the logic should go in a helper and then we indent the output (or the helper handles the indent). If you're willing to implement that, it'd nice otherwise we can merge as-is

**Comment by sebbrandt87** [comment]
Gimme some more minutes. I should be able to do it. 😄

**Comment by sebbrandt87** [comment]
@vboulineau @clamoriniere wdyt 😉

**Comment by sebbrandt87** [comment]
I did again a rebase to match with latest main branch changes.

**Review by clamoriniere — APPROVED** [review]
Thanks @sebbrandt87 for this contribution 👏 

It is a great added value 👍

**Pull request merged**
