### PR TITLE
Bump runner version to v0.1.4-beta

### PR DESCRIPTION
**Pull request by merchristK**
## Description
Bump Private Actions Runner version in order to include recent GitLab changes. DD-Source changes https://github.com/DataDog/dd-source/pull/147598

### CODE REVIEW

**Comment by merchristK** [comment]
* **#1597** <a href="https://app.graphite.dev/github/pr/DataDog/helm-charts/1597?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @merchristK and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dd-gplassard — APPROVED** [review]

**Review by liubenjamin — APPROVED** [review]

**Pull request merged**
