### PR TITLE
[datadog-crds] update from operator 0.7.0

### PR DESCRIPTION
**Pull request by celenechang**
#### What this PR does / why we need it:

Update Datadog CRDs following release of Datadog-Operator 0.7.0

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [X] Chart Version bumped
- [X] `CHANGELOG.md` has beed updated
- [X] Variables are documented in the `README.md`

### CODE REVIEW

**Review by clamoriniere — APPROVED** [review]

**Comment by clamoriniere** [comment]
The CI errors are very weird...

**Comment by celenechang** [comment]
I suspect something went wrong with the yaml file generation; the files look much larger than they were previously

**Review by davidor — COMMENTED** [review]
I think this PR can be closed now, because https://github.com/DataDog/helm-charts/pull/381/ (and other related PRs) have been merged.

**Comment by celenechang** [comment]
closing due to #379

**Pull request closed without merging**
