### PR TITLE
Update Chart.yaml to fix Semver in Operator

### PR DESCRIPTION
**Pull request by RobertKeyser**
It looks like the fix for the following wasn't added to the operator helm chart:
* https://github.com/DataDog/datadog-operator/issues/565
* https://github.com/DataDog/helm-charts/issues/689

This changes the `datadog-crds` dependency version and the version of the chart itself.

#### What this PR does / why we need it:

The noted fixes are not reflected in the datadog-operator chart yet because its version hasn't been updated.

#### Which issue this PR fixes

* https://github.com/DataDog/datadog-operator/issues/565
* https://github.com/DataDog/helm-charts/issues/689

#### Checklist
- [ ] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [x] Chart Version bumped
- [x] `CHANGELOG.md` has been updated

### CODE REVIEW

**Review by alai97 — COMMENTED** [review]
No docs review required.

**Review by CharlyF — APPROVED** [review]

**Comment by CharlyF** [comment]
Thanks for this @RobertKeyser - Would you mind updating this
```
+++ b/charts/datadog-operator/README.md
@@ -1,6 +1,6 @@
 # Datadog Operator
 
-![Version: 0.8.5](https://img.shields.io/badge/Version-0.8.5-informational?style=flat-square) ![AppVersion: 0.8.1](https://img.shields.io/badge/AppVersion-0.8.1-informational?style=flat-square)
+![Version: 0.8.6](https://img.shields.io/badge/Version-0.8.6-informational?style=flat-square) ![AppVersion: 0.8.1](https://img.shields.io/badge/AppVersion-0.8.1-informational?style=flat-square)
```

**Comment by RobertKeyser** [comment]
> Thanks for this @RobertKeyser - Would you mind updating this
> 
> ```
> +++ b/charts/datadog-operator/README.md
> @@ -1,6 +1,6 @@
>  # Datadog Operator
>  
> -Version: 0.8.5 AppVersion: 0.8.1
> +Version: 0.8.6 AppVersion: 0.8.1
> ```

Done with commit https://github.com/DataDog/helm-charts/pull/710/commits/291654f1f5b61af715d73dcfd447b1a189547c19

**Comment by CharlyF** [comment]
failure is unrelated.
Thank you for this contribution!

**Pull request merged**
