### PR TITLE
Fix a few typos on otel agent in values.yaml

### PR DESCRIPTION
**Pull request by songy23**
#### What this PR does / why we need it:

Fix typos: trace-agent -> otel-agent

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [x] `CHANGELOG.md` has been updated
- [x] Variables are documented in the `README.md`
- [ ] For Datadog Operator chart or value changes update the test baselines (run: `make update-test-baselines`)

### CODE REVIEW

**Review by clamoriniere — COMMENTED** [review]
Hi @songy23 

thanks for the typo finding and opening this pull request.
the comment changes are good, however you need to update the chart version and follow the github pull request checklist to trigger a new release of the chart with the typo fixes.

**Comment by songy23** [comment]
Thank you @clamoriniere , I have updated the PR with version bump and docs

**Review by krlv — APPROVED** [review]
LGTM 👍 Thanks @songy23 
Please rebase with the latest `main` branch (the latest chart version is `3.70.7` as of now)

**Review by dineshg13 — APPROVED** [review]

**Review by clamoriniere — APPROVED** [review]

**Pull request merged**
