### PR TITLE
Added time related syscalls to system-probe seccomp

### PR DESCRIPTION
**Pull request by mftoure**
#### What this PR does / why we need it:

This PR aims to add time related syscalls to the system-probe seccomp. 

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [x] `CHANGELOG.md` has been updated
- [ ] Variables are documented in the `README.md`

### CODE REVIEW

**Comment by brycekahle** [comment]
@mftoure do you know what code change in the agent added the need for these syscalls?

**Review by khewonc — APPROVED** [review]

**Comment by mftoure** [comment]
> @mftoure do you know what code change in the agent added the need for these syscalls?

There is no change in the agent code, but rather an existing test calling "touch" that was failing for the longest time due to these time related syscalls missing.

**Comment by brycekahle** [comment]
> an existing test calling "touch"

Is this something that ships to customers, or is internal only?

**Comment by mftoure** [comment]
> > an existing test calling "touch"
> 
> Is this something that ships to customers, or is internal only?

Yes, it's part of the system-probe's self_tests

**Review by brycekahle — APPROVED** [review]

**Pull request merged**
