### PR TITLE
FIX Capabilities.APIVersions check on datadog-crds chart

### PR DESCRIPTION
**Pull request by anthonyhaussman**
#### What this PR does / why we need it:
Actual templates check `.Capabilities.APIVersions` has the "apiextensions.k8s.io/v1/CustomResourceDefinition" resource present.

Via a `helm template` command with a recent version of Kubernetes, the template always returns the `apiextensions.k8s.io/v1beta1` apiVersion.

Only checking if the "apiextensions.k8s.io/v1" version is present seems to be enough to set the correct apiVersion.
Tested on Kubernetes `v1.22.7` with helm `v3.8.0`.

#### Checklist
- [X] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [X] Chart Version bumped
- [X] `CHANGELOG.md` has been updated

### CODE REVIEW

**Comment by clamoriniere** [comment]
hi @anthonyhaussman 
thanks for opening this pull request.

quick question before digging into the code change. Does it still work with older helm version?

**Comment by anthonyhaussman** [comment]
> hi @anthonyhaussman thanks for opening this pull request.
> 
> quick question before digging into the code change. Does it still work with older helm version?

Hi @clamoriniere :wave: 

So I have tested with helm `v2.16.7` / Kubernetes `v1.22.7`.
It still returns me the `apiextensions.k8s.io/v1beta1` apiVersion with the fix.

Tested with the current chat and it returns me  `apiextensions.k8s.io/v1beta1`  too.

Unfortunately, old helm versions do not change the behavior. :confused:

**Comment by anthonyhaussman** [comment]
At reading the Helm Version Support Policy (https://helm.sh/docs/topics/version_skew/), `2.16.x` helm version supports Kubernetes `1.16.x - 1.15.x`.

**Comment by vboulineau** [comment]
@anthonyhaussman You cannot bump `datadog-crd` version in other charts yet as it requires an update to `Chart.lock` which needs to be done once the version is published (two steps required)

**Comment by anthonyhaussman** [comment]
> @anthonyhaussman You cannot bump `datadog-crds` version in other charts yet as it requires an update to `Chart.lock` which needs to be done once the version is published (two steps required)

Alright, I revert the commit.

**Comment by anthonyhaussman** [comment]
@vboulineau and it's done :slightly_smiling_face:

**Review by vboulineau — APPROVED** [review]

**Pull request merged**
