### PR TITLE
feat(origin-detection): add unified setting

### PR DESCRIPTION
**Pull request by wdhif**
#### What this PR does / why we need it:

Add a new Global setting for the Origin Detection Unified setting of the Agent. This setting is a global one as it control Origin Detection behaviour for multiple Operator features (APM and DogStatsD).

#### Special notes for your reviewer:

Using the following chart:
```
➜  helm cat enabled.yaml
registry: public.ecr.aws/datadog
datadog:
  clusterName: wassim-minikube
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  originDetectionUnified:
    enabled: true
  kubelet:
    tlsVerify: false
    coreCheck: true
agents:
  image:
    tag: 7.54.0-rc.3-jmx
  env:
  - name: DD_TELEMETRY_ENABLED
    value: true
```

You should see:
```
➜  helm k exec -it datadog-agent-56tr4 -- agent config | grep unified
Defaulted container "agent" out of: agent, trace-agent, process-agent, init-volume (init), init-config (init)
origin_detection_unified: true
```

Using the following chart:
```
➜  helm cat enabled.yaml
registry: public.ecr.aws/datadog
datadog:
  clusterName: wassim-minikube
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  kubelet:
    tlsVerify: false
    coreCheck: true
agents:
  image:
    tag: 7.54.0-rc.3-jmx
  env:
  - name: DD_TELEMETRY_ENABLED
    value: true
```

You should see:
```
➜  helm k exec -it datadog-agent-jrsk5 -- agent config | grep unified
Defaulted container "agent" out of: agent, trace-agent, process-agent, init-volume (init), init-config (init)
origin_detection_unified: false
```

#### Checklist

- [x] Chart Version bumped
- [x] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [x] `CHANGELOG.md` has been updated
- [x] Variables are documented in the `README.md`
- [ ] For Datadog Operator chart or value changes update the test baselines (run: `make update-test-baselines`)

### CODE REVIEW

**Review by zhuminyi — APPROVED** [review]

**Comment by wdhif** [comment]
Waiting for `7.54.0` release.

**Review by clamoriniere — APPROVED** [review]

**Pull request merged**
