### PR TITLE
fix(datadog): update `collectedEventTypes` field documentation

### PR DESCRIPTION
**Pull request by aquiladayc**
#### What this PR does / why we need it:
Fix comment

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [ ] `CHANGELOG.md` has been updated
- [ ] Variables are documented in the `README.md`

### CODE REVIEW

**Comment by levan-m** [comment]
Could you please run `.github/helm-docs.sh` to update the readme file with the comment change?

**Comment by aquiladayc** [comment]
> Could you please run `.github/helm-docs.sh` to update the readme file with the comment change?

**Comment by aquiladayc** [comment]
> > Could you please run `.github/helm-docs.sh` to update the readme file with the comment change?

Nothing seems generated. Is there any specific way to do it? @levan-m 

```
% ./helm-docs.sh
INFO[2023-06-23T13:24:21+09:00] Found Chart directories []                   
% git status    
On branch akira-valueyaml-comment
Your branch is up to date with 'origin/akira-valueyaml-comment'.

nothing to commit, working tree clean
```

**Comment by levan-m** [comment]
Script uses `helm-docs` which searches for charts recursively from the current folder. Please run `.github/helm-docs.sh` from the root folder.

**Comment by aquiladayc** [comment]
> Script uses `helm-docs` which searches for charts recursively from the current folder. Please run `.github/helm-docs.sh` from the root folder.

Done, thanks. @levan-m

**Review by clamoriniere — APPROVED** [review]

**Pull request merged**
