### PR TITLE
Update Kube-State-Metrics Dependency to more recent version

### LINKED ISSUE #620: Kube-State-Metrics Dependency Very Old
**Describe what happened:**
The DataDog Helm chart has Kube-State-Metrics added as a dependency in requirements.yaml, however, the version here is very old, over a year.
```
  - name: kube-state-metrics
    version: 2.13.2
    repository: https://prometheus-community.github.io/helm-charts
    condition: datadog.kubeStateMetricsEnabled
```

The current release is 4.7.0. As you might expect, when trying to install this chart our security scanner picks up a large number of vulnerabilities on this very old image.

**Describe what you expected:**

Dependencies versions to be upgraded regularly to keep up to date

**Steps to reproduce the issue:**

View https://github.com/DataDog/helm-charts/blob/main/charts/datadog/requirements.yaml 

**Additional environment details (Operating System, Cloud provider, etc):**

### PR DESCRIPTION
**Pull request by sam-cogan**
#### What this PR does / why we need it:
This PR updates the dependency on Kube-State-Metrics in the DataDog helm chart to a more recent version to avoid issues with security vulnerabilities and errors in more recent versions of Kubernetes

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #620

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [x] Chart Version bumped
- [x] `CHANGELOG.md` has been updated
- [ ] Variables are documented in the `README.md`

### CODE REVIEW

**Review by maycmlee — APPROVED** [review]
👍  for docs.

**Comment by clamoriniere** [comment]
Hi @sam-cogan 

Updating the chart from `2.13.2` to `4.7.0` is not possible because it will update the `kube-state-metrics` version from `1.9.8` to a version`2.x.y`. But the `kubernetes_state` python check doesn't support "KSM v2" due to none backward compatibility change in `kube-state-metrics`.

The solution that I can propose is to use instead the `kubernetes_state_core` check that is based on the `kube-state-metrics` `v2` version. 
It will solve the different issues that you have mentioned:
* remove the need to deploy the `kube-state-metrics` chart as `datadog` chart dependency and so its vulnerabilities.
* remove deprecation warning logs
* removed vulnerability (we take care of updating dependencies in the agent image when it is needed)

you can find more info about the `kubernetes_state_core` check with the following links:
* https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm
* https://www.datadoghq.com/blog/kube-state-metrics-v2-monitoring-datadog/

to enabled it, your `values.yaml` must be updated with
```yaml
datadog:
  #...
  kubeStateMetricsEnabled: false  # uninstall kube-state-metrics chart
  kubeStateMetricsCore:
    enabled: true                 # enable `kubernetes_state_core` check
    ignoreLegacyKSMCheck: true    # disable `kubernetes_state` check
  #...
```

please let us know if the proposed solution works for you.

**Comment by sam-cogan** [comment]
Apologies for the delay, yes removing kube-state-metrics altogether works

**Comment by wyardley** [comment]
Just a heads up: GKE 1.22 also seems unhappy about the (crusty) version of KSM hitting all these endpoint, and may even prevent upgrades when it's seeing those requests. It was somewhat tricky to track down where these requests were coming from. So, I think this may help for us as well, but guessing this will likely continue to be a problem for people running >= 1.22, esp. if / when the affected deprecated API requests are removed vs. deprecated.

**Pull request closed without merging**
