### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by jfairchild**
#### What this PR does / why we need it:
Typo in comment

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

* [x]  Chart Version bumped
* [x]  `CHANGELOG.md` has been updated
* [x]  Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
* [x]  Variables are documented in the `README.md`

### CODE REVIEW

**Comment by clamoriniere** [comment]
Hi @jfairchild 

please follow the check list present in the pull request template

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] `CHANGELOG.md` has been updated
- [ ] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [ ] Variables are documented in the `README.md`

**Comment by jfairchild** [comment]
> Hi @jfairchild
> 
> please follow the check list present in the pull request template
> 
> #### Checklist
> [Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
> 
> * [ ]  Chart Version bumped
> * [ ]  `CHANGELOG.md` has been updated
> * [ ]  Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
> * [ ]  Variables are documented in the `README.md`

OK, I removed the first 2 because I figured this was a small change. (No functional changes.)

**Comment by clamoriniere** [comment]
hi @jfairchild 

Even if the PR changes only apply to the doc, bumping the patch digit of the chart version is mandatory, because it is what triggers a release. If we want to see the change on https://artifacthub.io/packages/helm/datadog/datadog it needs to be part of a new version.

so please bump the version in the chart.yaml file and run again the `.github/helm-docs.sh` 🙇

**Review by clamoriniere — CHANGES_REQUESTED** [review]
hi @jfairchild 

Even if the PR changes only apply to the doc, bumping the patch digit of the chart version is mandatory, because it is what triggers a release. If we want to see the change on https://artifacthub.io/packages/helm/datadog/datadog it needs to be part of a new version.

so please bump the version in the chart.yaml file and run again the `.github/helm-docs.sh` 🙇

**Comment by jfairchild** [comment]
> hi @jfairchild
> 
> Even if the PR changes only apply to the doc, bumping the patch digit of the chart version is mandatory, because it is what triggers a release. If we want to see the change on https://artifacthub.io/packages/helm/datadog/datadog it needs to be part of a new version.
> 
> so please bump the version in the chart.yaml file and run again the `.github/helm-docs.sh` 🙇

Thank you for explaining all this to me 😅 
I've made the changes and updated the PR template checklist ✅

**Review by clamoriniere — APPROVED** [review]

**Comment by clamoriniere** [comment]
@jfairchild 

thanks for your quick update. I just merged your PR 🥳

**Pull request merged**
