### PR TITLE
Fix typo in allowHostPorts

### LINKED ISSUE #10: unknown field "+allowHostPorts"
**Describe what happened:**
Cannot apply the helm chart on our OpenShift cluster, when SCC is enabled:
```
  Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(SecurityContextConstraints): unknown field "+allowHostPorts" in com.github.openshift.api.security.v1.SecurityContextConstraints, ValidationError(SecurityContextConstraints.seLinuxContext): unknown field "rule" in com.github.openshift.api.security.v1.SELinuxContextStrategyOptions, ValidationError(SecurityContextConstraints): missing required field "allowHostPorts" in com.github.openshift.api.security.v1.SecurityContextConstraints]
  Error: plugin "diff" exited with error
```
There is a typo in the allowHostPorts field.

**Steps to reproduce the issue:**
apply the helm chart on OpenShift

**Additional environment details (Operating System, Cloud provider, etc):**
OpenShift 4.4 + Helm 3

### PR DESCRIPTION
**Pull request by cyberox**
#### What this PR does / why we need it:
Fix the typo "+allowHostPorts" 

#### Which issue this PR fixes
 - fixes #10 

#### Checklist
- [X] Chart Version bumped

### CODE REVIEW

**Comment by vboulineau** [comment]
Hi @cyberox,

You will need to bump Chart version to pass CI

**Comment by cyberox** [comment]
I also fixed another incorrect setting in the SCC file, and bumped the chart

**Comment by cyberox** [comment]
@vboulineau I've bumped the chart, could you please verify this PR?

**Comment by vboulineau** [comment]
Thanks @cyberox. I'll merge this PR as it fixes some issues, though I'm not sure we want to remove `rule/type: MustRunAs` from `values.yaml`.

I'll backlog a ticket on our side to allow customization of `rule/type` without breaking PSP/SCC.

**Pull request merged**
