### PR TITLE
usm: Remove private beta comments

### PR DESCRIPTION
**Pull request by guyarb**
#### What this PR does / why we need it:

Removes old comment about "private beta".

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [x] `CHANGELOG.md` has been updated
- [ ] Variables are documented in the `README.md`

### CODE REVIEW

**Comment by guyarb** [comment]
Should I bump the chart in such scenario?

**Review by AliDatadog — APPROVED** [review]

**Review by AliDatadog — CHANGES_REQUESTED** [review]
let's bump the chart version so it gets published

**Comment by guyarb** [comment]
@AliDatadog done

**Comment by guyarb** [comment]
@AliDatadog can you merge?

**Review by levan-m — APPROVED** [review]

**Pull request merged**
