### PR TITLE
[extended-daemon-set] Add CRDs inside the chart

### PR DESCRIPTION
**Pull request by clamoriniere**
#### What this PR does / why we need it:

* Add ExtendedDaemonset CRDs directly inside this chart.

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [ ] Chart Version bumped
- [ ] `CHANGELOG.md` has beed updated
- [ ] Variables are documented in the `README.md`

### CODE REVIEW

**Comment by vboulineau** [comment]
I believe it removes the ability to NOT install the CRDs

**Comment by clamoriniere** [comment]
> I believe it removes the ability to NOT install the CRDs

Yes, to you think I should add back this capability? I don't see a real use case for it

**Comment by vboulineau** [comment]
I agree the use case i thin, but I think some customers may handle CRDs without Helm and it may be useful it case something goes wrong during Helm release lifecycle for some reason.

**Review by davidor — COMMENTED** [review]
I think it would be nice to have some tooling, like the `update-crds.sh` script that we used before, to fetch the CRDs from the EDS repo.

**Review by vboulineau — APPROVED** [review]

**Comment by clamoriniere** [comment]
> I think it would be nice to have some tooling, like the `update-crds.sh` script that we used before, to fetch the CRDs from the EDS repo.

@davidor pull request updated with the script and doc

**Review by davidor — APPROVED** [review]
Looks good to me :+1:

In a different PR we can try to provide a shared script to update the CRDs.
The one introduced in this PR is almost identical to the one we have under `datadog-crds`. It'd be nice to avoid this duplication.

**Pull request merged**
