### PR TITLE
Private action runner helm chart YAML formatting tweaks

### PR DESCRIPTION
**Pull request by oliverli**
#### What this PR does / why we need it:

Extremely small PR to fix the formatting of the PAR YAML files:

- Switch from JSON list notation to the more canonical YAML list notation
- whitespace in actionsAllowlist examples that fixes alignment of the list elements when e.g. using Cmd+/ to uncomment the lines in an editor

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

NA

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] `CHANGELOG.md` has been updated

### CODE REVIEW

**Comment by oliverli** [comment]
* **#1499** <a href="https://app.graphite.dev/github/pr/DataDog/helm-charts/1499?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @oliverli and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ksun154 — APPROVED** [review]
thanks for fixing!

**Review by irubnich — APPROVED** [review]

**Pull request merged**
