### PR TITLE
[ASCII-2204] Update fips-proxy image tag to 1.1.4 release

### PR DESCRIPTION
**Pull request by jeremy-hanna**
#### What this PR does / why we need it:

This PR updates the fips-proxy tag to use the [latest release 1.1.4](https://github.com/DataDog/fips-proxy/releases/tag/1.1.4) in the helm chart

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [x] `CHANGELOG.md` has been updated
- [x] Variables are documented in the `README.md`
- [ ] For Datadog Operator chart or value changes update the test baselines (run: `make update-test-baselines`)

### CODE REVIEW

**Review by levan-m — APPROVED** [review]

**Comment by jeremy-hanna** [comment]
@levan-m could you please merge this? thanks!

**Pull request merged**
