### PR TITLE
Fix envFrom indentation in synthetics-private-location

### PR DESCRIPTION
**Pull request by tmcg-gusto**
#### What this PR does / why we need it:
0.15.29 breaks the indentation of `envFrom` in the `synthetics-private-location` deployment template. This adjusts the templating to use the same `{{-` and `nindent` that other variables use.

Tested locally by uncommenting the example `envFrom` in `values.yaml`:
Before this change:
`$ cd charts/synthetics-private-location`
`$ helm template .`
```
Error: YAML parse error on synthetics-private-location/templates/deployment.yaml: error converting YAML to JSON: yaml: line 41: did not find expected key

Use --debug flag to render out invalid YAML
```
After this change:
Valid yaml.

Tested with:
```
$ helm version
version.BuildInfo{Version:"v3.10.2", GitCommit:"50f003e5ee8704ec937a756c646870227d7c8b58", GitTreeState:"clean", GoVersion:"go1.19.3"}
```

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Chart Version bumped
- [X] Documentation has been updated with helm-docs (run: `.github/helm-docs.sh`)
- [X] `CHANGELOG.md` has been updated
- [X] Variables are documented in the `README.md`
- [X] For Datadog Operator chart or value changes update the test baselines (run: `make update-test-baselines`)

### CODE REVIEW

**Review by ruizb — APPROVED** [review]
My bad on this one! Thanks for fixing it 🙇

**Comment by tmcg-gusto** [comment]
@ruizb All good! 

Just rebased and got all the commits signed properly (apparently I didn't have that enabled by default). Anything left to do on my end?

**Comment by protoz** [comment]
Any chance you can also add nindent to
https://github.com/DataDog/helm-charts/blob/ceb3d1618654d7770ba14d4738ab78422c9f657b/charts/synthetics-private-location/templates/deployment.yaml#L79C31-L79C32

This is also broken for env.

**Comment by ruizb** [comment]
> Anything left to do on my end?

No, all good! I'm waiting for the CI to pass before merging, I forgot to do it last time ^^'

> This is also broken for env.

Let me create a quick PR to fix 👍 Thank you for reporting!

**Pull request merged**
